name: CI

on:
  push:
  pull_request:

jobs:
  build-and-benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update || true
          brew install libomp || true
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cd build
          cmake --build . --config Release -- -j
      - name: Run benchmark
        run: |
          cd build
          ./OpenMP_Mini1_Project_app || true
