name: CI

on:
  push:
  pull_request:

jobs:
  build-and-benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update || true
          brew install libomp || true
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cd build
          cmake --build . --config Release -- -j
      - name: Run benchmark
        run: |
          cd build
          ./OpenMP_Mini1_Project_app || true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib pandas
      - name: Generate benchmark artifacts
        run: |
          python scripts/generate_bench_assets.py
      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
            name: bench-artifacts-${{ matrix.os }}
            path: |
              bench_artifacts/*.csv
              bench_artifacts/*.md
              bench_artifacts/*.png
              bench_artifacts/*.svg
              bench_artifacts/*.json
